### ISSUE TITLE
Removing a session when user logs out

### ISSUE THREAD

**Issue by theyak** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#2]
Is there a way to kill a session if a user logs out from the remote website. I've tried things like $session->unpersist() and $session->clear() to no avail. If someone knows how and can put this in the example it would be greatly appreciated.

**Comment by fnk** [comment]
Sorry for the late reply, just came back from holidays. I will look into this today.

**Comment by fnk** [comment]
This extension is built around ImmutableSessionProviderWithCookie.
Immutable sessions in Mediawiki are not supposed get logged out: https://github.com/wikimedia/mediawiki/blob/master/includes/user/User.php#L3815
If you really need to kill the session you might want to try https://github.com/tentwentyfour/remoteauth-ng which extends CookieSessionProvider.
