### ISSUE TITLE
Poblems with lockdown extension

### ISSUE THREAD

**Issue by gbonazzoli** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#3]
On a **mediawiki 1.27.1** with **mediawiki-extensions-Lockdown-REL1_27.zip** installed you get at the very first login the errors reported at the end of the email. 

If you reload the page you get a mediawiki **Permission error** and if you press **Login** in the upper right corner of mediawiki you get a **Cannot log in now - Logging in is not possible when using AuthRemoteuser sessions**, but in reality you can enter the wiki, and from now on it works like a charm.

```
[5815c367bc2341d090091a85] /wikis/ced/index.php/Main_Page MWException from line 3811 of /samba/public/phpapps/wikis/ced/includes/user/User.php: CAS update failed on user_touched for user ID '2' (read from slave); the version of the user to be saved is older than the current version.

Backtrace:

#0 /samba/public/phpapps/wikis/ced/extensions/AuthRemoteuser/AuthRemoteuser.body.php(137): User->saveSettings()
#1 /samba/public/phpapps/wikis/ced/extensions/AuthRemoteuser/AuthRemoteuser.body.php(100): AuthRemoteuser->initUser(User, string)
#2 /samba/public/phpapps/wikis/ced/extensions/AuthRemoteuser/AuthRemoteuser.body.php(64): AuthRemoteuser->newSessionForRequest(string, WebRequest)
#3 /samba/public/phpapps/wikis/ced/includes/session/SessionManager.php(479): AuthRemoteuser->provideSessionInfo(WebRequest)
#4 /samba/public/phpapps/wikis/ced/includes/session/SessionManager.php(182): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#5 /samba/public/phpapps/wikis/ced/includes/WebRequest.php(700): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#6 /samba/public/phpapps/wikis/ced/includes/session/SessionManager.php(121): WebRequest->getSession()
#7 /samba/public/phpapps/wikis/ced/includes/Setup.php(747): MediaWiki\Session\SessionManager::getGlobalSession()
#8 /samba/public/phpapps/wikis/ced/includes/WebStart.php(137): require_once(string)
#9 /samba/public/phpapps/wikis/ced/index.php(40): require(string)
#10 {main}
```

**Comment by fnk** [comment]
This seems to be related to this, unfixed, bug: https://phabricator.wikimedia.org/T95839
I'll try to work around this.

**Comment by fnk** [comment]
I cannot reproduce that bug but i know that one of my colleagues also had this problem and produced the exact same log entries.
I still think that is related to the bug mentioned above so i did some changes to catch this case.
Can you please pull 3d1894573048d6e508e190ab15ca5f9856752578 and see if the problem persists?

Thanks,
Andi.

**Comment by gbonazzoli** [comment]
Hi Andreas,

it seems to work.  I will check better tomorrow and let you know !

Thanks
