### ISSUE TITLE
When cookie has invalid session id, it goes to a login page instead of authenticating.

### ISSUE THREAD

**Issue by DreDub2k** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#6]
This extensions works pretty great, but there was an issue I was having when I would access the site from other PCs or after leaving the browser idle until the session is no longer valid.

Instead of logging in automatically it would go to the page asking to login, at that point if I refresh or click another link, the extension works normally. This annoyed me greatly so I did a bunch of digging and found a fix.

In the provideSessionInfo function of AuthRemoteuser.body.php if you change this line:

`if (null === $id) {`

into 

`if ((null === $id)||(!MediaWiki\Session\SessionManager::singleton()->getSessionById($id))) {`

It will assign a new sessionid if the id is null or if the session is no longer valid, which means no more annoying login page.

**Comment by fnk** [comment]
Thanks for the fix!
I added that in commit https://github.com/noris-network/mediawiki-extensions-sessionprovider-remoteuser/commit/84949ebcb6a7bb5b4d74ee759c754636db52dc6d
