### ISSUE TITLE
Mediawiki 1.27.1 maintenance/rebuildall.php does not end properly

### ISSUE THREAD

**Issue by gbonazzoli** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#7]
Mediawiki 1.27.1 maintenance/rebuildall.php does not end properly if 

wfLoadExtension( 'AuthRemoteuser' );

is present LocalSettings.php (without extension there is no problem at all). 

The errors reported are:

Refreshing links tables.
Starting from page_id 1 of 9377.
Bonaz 1
Exception encountered, of type "InvalidArgumentException"
[6eff8ff8c3eaec2104f17746] [no req]   InvalidArgumentException from line 97 of /samba/public/phpapps/wikis/ced/extensions/AuthRemoteuser/AuthRemoteuser.body.php: Invalid user name
Backtrace:
#0 /samba/public/phpapps/wikis/ced/extensions/AuthRemoteuser/AuthRemoteuser.body.php(64): AuthRemoteuser->newSessionForRequest(string, FauxRequest)
#1 /samba/public/phpapps/wikis/ced/includes/session/SessionManager.php(479): AuthRemoteuser->provideSessionInfo(FauxRequest)
#2 /samba/public/phpapps/wikis/ced/includes/session/SessionManager.php(182): MediaWiki\Session\SessionManager->getSessionInfoForRequest(FauxRequest)
#3 /samba/public/phpapps/wikis/ced/includes/WebRequest.php(700): MediaWiki\Session\SessionManager->getSessionForRequest(FauxRequest)
#4 /samba/public/phpapps/wikis/ced/includes/user/User.php(1203): WebRequest->getSession()
#5 /samba/public/phpapps/wikis/ced/includes/user/User.php(408): User->loadFromSession()
#6 /samba/public/phpapps/wikis/ced/includes/user/User.php(5043): User->load()
#7 /samba/public/phpapps/wikis/ced/includes/user/User.php(2750): User->loadOptions()
#8 /samba/public/phpapps/wikis/ced/includes/context/RequestContext.php(363): User->getOption(string)
#9 /samba/public/phpapps/wikis/ced/includes/specialpage/SpecialPageFactory.php(612): RequestContext->getLanguage()
#10 /samba/public/phpapps/wikis/ced/includes/parser/Parser.php(3622): SpecialPageFactory::capturePath(Title, RequestContext)
#11 /samba/public/phpapps/wikis/ced/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#12 /samba/public/phpapps/wikis/ced/includes/parser/Parser.php(3366): PPFrame_DOM->expand(PPNode_DOM, integer)
#13 /samba/public/phpapps/wikis/ced/includes/parser/Parser.php(1248): Parser->replaceVariables(string)
#14 /samba/public/phpapps/wikis/ced/includes/parser/Parser.php(446): Parser->internalParse(string)
#15 [internal function]: Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#16 /samba/public/phpapps/wikis/ced/includes/StubObject.php(105): call_user_func_array(array, array)
#17 /samba/public/phpapps/wikis/ced/includes/StubObject.php(129): StubObject->_call(string, array)
#18 /samba/public/phpapps/wikis/ced/includes/content/WikitextContent.php(331): StubObject->__call(string, array)
#19 /samba/public/phpapps/wikis/ced/includes/content/WikitextContent.php(331): StubObject->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#20 /samba/public/phpapps/wikis/ced/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#21 /samba/public/phpapps/wikis/ced/includes/content/AbstractContent.php(230): AbstractContent->getParserOutput(Title, NULL, NULL, boolean)
#22 /samba/public/phpapps/wikis/ced/maintenance/refreshLinks.php(242): AbstractContent->getSecondaryDataUpdates(Title)
#23 /samba/public/phpapps/wikis/ced/maintenance/refreshLinks.php(172): RefreshLinks::fixLinksFromArticle(integer)
#24 /samba/public/phpapps/wikis/ced/maintenance/refreshLinks.php(58): RefreshLinks->doRefreshLinks(NULL, boolean, NULL, boolean, boolean)
#25 /samba/public/phpapps/wikis/ced/maintenance/rebuildall.php(60): RefreshLinks->execute()
#26 /samba/public/phpapps/wikis/ced/maintenance/doMaintenance.php(103): RebuildAll->execute()
#27 /samba/public/phpapps/wikis/ced/maintenance/rebuildall.php(67): require_once(string)
#28 {main}

**Comment by fnk** [comment]
Thanks for reporting this, i will look into it on monday/tuesday.

**Comment by fnk** [comment]
Hi gbonazzoli.
We had the same problem. You can solve it by setting a user name as environment variable before running a maintenance script. Like or mod_auth_x would do it.

```
# REMOTE_USER=someadminusername
# php5 maintenance/rebuildall.php
```

Cheers,
Andi.
